# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data111',
            table='Data111',
        ),
    ]
