# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171213_1926'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data111',
            table='data111',
        ),
    ]
