# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_update'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Update',
        ),
    ]
