# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171213_1948'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data222',
            table='Data222',
        ),
    ]
