# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_document_historicaldata111_historicaldocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldata111',
            name='kolichestvo_licevyh_schetov_v_reestre',
            field=models.IntegerField(blank=True, db_column='Количество_лицевых_счетов_в_реестре', default=None, null=True),
        ),
    ]
