# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_data_korp_kontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_korp_kontrol',
            name='polucheno_1_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_korp_kontrol',
            name='polucheno_1_1_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='data_korp_kontrol',
            name='polucheno_1_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data_korp_kontrol',
            name='polucheno_1_2_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='data_korp_kontrol',
            name='predpisanie_ob_istrebovanii_documentov',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='data_korp_kontrol',
            name='prepsanie_ob_ustranenii_narusheniya_zakonodatelstva_RF',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='data_korp_kontrol',
            name='zapros_o_predostavlenii_informacii',
            field=models.BooleanField(default=False),
        ),
    ]
