# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180303_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_korp_kontrol',
            old_name='polucheno_1_1',
            new_name='polucheno_1_3',
        ),
        migrations.RenameField(
            model_name='data_korp_kontrol',
            old_name='polucheno_1_1_bool',
            new_name='polucheno_1_3_bool',
        ),
    ]
